server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端得示例名称
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 10
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
    healthcheck:
      enabled: true
  server:
    eviction-interval-timer-in-ms: 10000
